project_name: "ghost"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./main.go
    binary: ghost
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - "7"
archives:
  - format_overrides:
      - goos: windows
        format: zip